from typing import Any, Protocol

class AsyncDatabaseHandlerProtocol(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    async def execute(self, query: str, *args: Any) -> Any: ...
