from typing import Any, Protocol

class SyncDatabaseHandlerProtocol(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def execute(self, query: str, *args: Any) -> Any: ...
