# Роли пользователей
class UserRoles:
    ADMIN = "admin"
    MANAGER = "manager"

    ALL_ROLES = [ADMIN, MANAGER]


# Коды ошибок
class ErrorCodes:
    # Валидация
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Аутентификация
    TOKEN_REQUIRED = "TOKEN_REQUIRED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"

    # Авторизация
    ADMIN_REQUIRED = "ADMIN_REQUIRED"
    INSUFFICIENT_PRIVILEGES = "INSUFFICIENT_PRIVILEGES"

    # Пользователи
    USERNAME_EXISTS = "USERNAME_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    SELF_DELETE_FORBIDDEN = "SELF_DELETE_FORBIDDEN"
    SELF_ROLE_CHANGE_FORBIDDEN = "SELF_ROLE_CHANGE_FORBIDDEN"
    LAST_ADMIN_DELETE_FORBIDDEN = "LAST_ADMIN_DELETE_FORBIDDEN"
    LAST_ADMIN_DEMOTE_FORBIDDEN = "LAST_ADMIN_DEMOTE_FORBIDDEN"


class TokenSettings:
    ACCESS_TOKEN_LIFETIME_HOURS = 2
    REFRESH_TOKEN_LIFETIME_DAYS = 30


class ValidationRules:
    MIN_USERNAME_LENGTH = 3
    MIN_PASSWORD_LENGTH = 6
